
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN RPAREN LBRACE RBRACE ASSIGN SEMICOLON COMMA COLON NUMERAL STRING NAME\n    program : program statement\n    \n    program : statement\n    \n    statement : call SEMICOLON\n    \n    block : LBRACE program RBRACE\n    \n    call : NAME LPAREN arguments RPAREN\n    \n    call : NAME LPAREN RPAREN\n    \n    arguments : value\n    \n    arguments : arguments COMMA value\n    \n    value : variable\n          | constant\n          | block\n          | call\n    \n    variable : NAME\n    \n    constant : STRING\n             | NUMERAL\n    '
    
_lr_action_items = {'RPAREN':([6,9,10,11,12,13,14,15,16,17,18,21,22,23,],[16,21,-9,-14,-15,-11,-12,-10,-6,-7,-13,-5,-4,-8,]),'STRING':([6,20,],[11,11,]),'COMMA':([9,10,11,12,13,14,15,16,17,18,21,22,23,],[20,-9,-14,-15,-11,-12,-10,-6,-7,-13,-5,-4,-8,]),'LPAREN':([2,18,],[6,6,]),'LBRACE':([6,20,],[8,8,]),'RBRACE':([3,5,7,19,],[-2,-1,-3,22,]),'$end':([1,3,5,7,],[0,-2,-1,-3,]),'NAME':([0,1,3,5,6,7,8,19,20,],[2,2,-2,-1,18,-3,2,2,18,]),'SEMICOLON':([4,16,21,],[7,-6,-5,]),'NUMERAL':([6,20,],[12,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,8,],[1,19,]),'block':([6,20,],[13,13,]),'constant':([6,20,],[15,15,]),'arguments':([6,],[9,]),'statement':([0,1,8,19,],[3,5,3,5,]),'variable':([6,20,],[10,10,]),'call':([0,1,6,8,19,20,],[4,4,14,4,4,14,]),'value':([6,20,],[17,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program statement','program',2,'p_program','yacker.py',10),
  ('program -> statement','program',1,'p_program_end','yacker.py',18),
  ('statement -> call SEMICOLON','statement',2,'p_statement','yacker.py',25),
  ('block -> LBRACE program RBRACE','block',3,'p_block','yacker.py',32),
  ('call -> NAME LPAREN arguments RPAREN','call',4,'p_call','yacker.py',39),
  ('call -> NAME LPAREN RPAREN','call',3,'p_call_empty','yacker.py',46),
  ('arguments -> value','arguments',1,'p_arguments_single','yacker.py',53),
  ('arguments -> arguments COMMA value','arguments',3,'p_arguments_list','yacker.py',60),
  ('value -> variable','value',1,'p_value','yacker.py',68),
  ('value -> constant','value',1,'p_value','yacker.py',69),
  ('value -> block','value',1,'p_value','yacker.py',70),
  ('value -> call','value',1,'p_value','yacker.py',71),
  ('variable -> NAME','variable',1,'p_variable','yacker.py',78),
  ('constant -> STRING','constant',1,'p_constant','yacker.py',85),
  ('constant -> NUMERAL','constant',1,'p_constant','yacker.py',86),
]
