
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN RPAREN LBRACK RBRACK LBRACE RBRACE ASSIGN MUTATE SEMICOLON COMMA NUMERAL STRING NAME program : program line  program : line  line : statement SEMICOLON \n    statement : function_call\n              | function block\n              | structure\n              | definition\n              | mutation\n     definition : lside ASSIGN rside  mutation : lside MUTATE rside \n    lside : NAME\n    \n    rside : value\n          | group\n    \n    value : NAME\n          | STRING\n          | NUMERAL\n     group : LPAREN argument_list RPAREN  block : LBRACE RBRACE  function_call : NAME LPAREN argument_list RPAREN  function_call : NAME LPAREN RPAREN  function : NAME NAME LPAREN RPAREN  function : NAME NAME LPAREN RPAREN NAME NAME  function : NAME NAME LPAREN parameter_list RPAREN  function : NAME NAME LPAREN parameter_list RPAREN NAME NAME  structure : NAME NAME LBRACK type_parameter_list RBRACK ASSIGN LPAREN parameter_list RPAREN structure : NAME NAME ASSIGN LPAREN parameter_list RPAREN type_parameter : NAME  type_parameter_list : type_parameter_list COMMA type_parameter  type_parameter_list : type_parameter  parameter : NAME NAME  parameter_list : parameter_list COMMA parameter  parameter_list : parameter  argument : value  argument : NAME ASSIGN value  argument_list : argument_list COMMA argument  argument_list : argument '
    
_lr_action_items = {'LBRACK':([17,],[34,]),'COMMA':([21,22,23,28,29,30,32,36,40,43,44,45,46,49,50,53,57,58,62,66,],[-14,-15,-16,-14,38,-36,-33,38,51,-32,-27,-29,56,-34,-35,-30,51,-31,-28,51,]),'LBRACE':([1,42,52,60,64,],[12,-21,-23,-22,-24,]),'RBRACK':([44,45,46,62,],[-27,-29,55,-28,]),'ASSIGN':([3,7,17,28,55,],[14,-11,35,37,61,]),'STRING':([13,14,16,20,37,38,],[22,22,22,22,22,22,]),'SEMICOLON':([4,5,8,9,10,11,19,21,22,23,24,25,26,27,31,39,48,63,67,],[-6,-8,-4,18,-7,-5,-18,-14,-15,-16,-12,-13,-10,-9,-20,-19,-17,-26,-25,]),'LPAREN':([7,13,14,17,35,61,],[16,20,20,33,47,65,]),'NAME':([0,2,6,7,13,14,15,16,18,20,33,34,37,38,41,42,47,51,52,54,56,59,65,],[7,-2,7,17,21,21,-1,28,-3,28,41,44,21,28,53,54,41,41,59,60,44,64,41,]),'MUTATE':([3,7,],[13,-11,]),'NUMERAL':([13,14,16,20,37,38,],[23,23,23,23,23,23,]),'RPAREN':([16,21,22,23,28,29,30,32,33,36,40,43,49,50,53,57,58,66,],[31,-14,-15,-16,-14,39,-36,-33,42,48,52,-32,-34,-35,-30,63,-31,67,]),'RBRACE':([12,],[19,]),'$end':([2,6,15,18,],[-2,0,-1,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'type_parameter':([34,56,],[45,62,]),'program':([0,],[6,]),'argument':([16,20,38,],[30,30,50,]),'mutation':([0,6,],[5,5,]),'statement':([0,6,],[9,9,]),'line':([0,6,],[2,15,]),'group':([13,14,],[25,25,]),'function':([0,6,],[1,1,]),'parameter_list':([33,47,65,],[40,57,66,]),'structure':([0,6,],[4,4,]),'block':([1,],[11,]),'lside':([0,6,],[3,3,]),'argument_list':([16,20,],[29,36,]),'rside':([13,14,],[26,27,]),'value':([13,14,16,20,37,38,],[24,24,32,32,49,32,]),'function_call':([0,6,],[8,8,]),'type_parameter_list':([34,],[46,]),'parameter':([33,47,51,65,],[43,43,58,43,]),'definition':([0,6,],[10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program line','program',2,'p_program','yacker.py',8),
  ('program -> line','program',1,'p_program_terminal','yacker.py',13),
  ('line -> statement SEMICOLON','line',2,'p_line','yacker.py',17),
  ('statement -> function_call','statement',1,'p_statement','yacker.py',22),
  ('statement -> function block','statement',2,'p_statement','yacker.py',23),
  ('statement -> structure','statement',1,'p_statement','yacker.py',24),
  ('statement -> definition','statement',1,'p_statement','yacker.py',25),
  ('statement -> mutation','statement',1,'p_statement','yacker.py',26),
  ('definition -> lside ASSIGN rside','definition',3,'p_definition','yacker.py',31),
  ('mutation -> lside MUTATE rside','mutation',3,'p_mutation','yacker.py',36),
  ('lside -> NAME','lside',1,'p_lside','yacker.py',41),
  ('rside -> value','rside',1,'p_rside','yacker.py',47),
  ('rside -> group','rside',1,'p_rside','yacker.py',48),
  ('value -> NAME','value',1,'p_value','yacker.py',56),
  ('value -> STRING','value',1,'p_value','yacker.py',57),
  ('value -> NUMERAL','value',1,'p_value','yacker.py',58),
  ('group -> LPAREN argument_list RPAREN','group',3,'p_group','yacker.py',63),
  ('block -> LBRACE RBRACE','block',2,'p_block','yacker.py',67),
  ('function_call -> NAME LPAREN argument_list RPAREN','function_call',4,'p_function_call','yacker.py',73),
  ('function_call -> NAME LPAREN RPAREN','function_call',3,'p_function_call_empty','yacker.py',77),
  ('function -> NAME NAME LPAREN RPAREN','function',4,'p_function_nothing','yacker.py',83),
  ('function -> NAME NAME LPAREN RPAREN NAME NAME','function',6,'p_function_no_parameters','yacker.py',87),
  ('function -> NAME NAME LPAREN parameter_list RPAREN','function',5,'p_function_no_return','yacker.py',91),
  ('function -> NAME NAME LPAREN parameter_list RPAREN NAME NAME','function',7,'p_function','yacker.py',95),
  ('structure -> NAME NAME LBRACK type_parameter_list RBRACK ASSIGN LPAREN parameter_list RPAREN','structure',9,'p_structure_parameterized','yacker.py',101),
  ('structure -> NAME NAME ASSIGN LPAREN parameter_list RPAREN','structure',6,'p_structure','yacker.py',105),
  ('type_parameter -> NAME','type_parameter',1,'p_type_parameter','yacker.py',111),
  ('type_parameter_list -> type_parameter_list COMMA type_parameter','type_parameter_list',3,'p_type_parameter_list','yacker.py',115),
  ('type_parameter_list -> type_parameter','type_parameter_list',1,'p_type_parameter_list_terminal','yacker.py',120),
  ('parameter -> NAME NAME','parameter',2,'p_parameter','yacker.py',126),
  ('parameter_list -> parameter_list COMMA parameter','parameter_list',3,'p_parameter_list','yacker.py',130),
  ('parameter_list -> parameter','parameter_list',1,'p_parameter_list_terminal','yacker.py',135),
  ('argument -> value','argument',1,'p_argument','yacker.py',141),
  ('argument -> NAME ASSIGN value','argument',3,'p_argument_kw','yacker.py',145),
  ('argument_list -> argument_list COMMA argument','argument_list',3,'p_argument_list','yacker.py',149),
  ('argument_list -> argument','argument_list',1,'p_argument_list_terminal','yacker.py',154),
]
